/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as RequestAccessRouteImport } from './routes/request-access'
import { Route as AuthenticatedApprovedRouteRouteImport } from './routes/_authenticated/_approved/route'
import { Route as AuthenticatedAccessRouteImport } from './routes/_authenticated/access'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as AuthenticatedApprovedAdminRouteImport } from './routes/_authenticated/_approved/admin'
import { Route as AuthenticatedApprovedDashboardRouteImport } from './routes/_authenticated/_approved/dashboard'
import { Route as AuthenticatedApprovedShowdownRouteImport } from './routes/_authenticated/_approved/showdown'
import { Route as AuthenticatedApprovedVaultRouteImport } from './routes/_authenticated/_approved/vault'
import { Route as ApiPublicHooksScoreShowdownRouteImport } from './routes/api/public/hooks/score-showdown'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestAccessRoute = RequestAccessRouteImport.update({
  id: '/request-access',
  path: '/request-access',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApprovedRouteRoute =
  AuthenticatedApprovedRouteRouteImport.update({
    id: '/_approved',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccessRoute = AuthenticatedAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApprovedAdminRoute =
  AuthenticatedApprovedAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedApprovedRouteRoute,
  } as any)
const AuthenticatedApprovedDashboardRoute =
  AuthenticatedApprovedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedApprovedRouteRoute,
  } as any)
const AuthenticatedApprovedShowdownRoute =
  AuthenticatedApprovedShowdownRouteImport.update({
    id: '/showdown',
    path: '/showdown',
    getParentRoute: () => AuthenticatedApprovedRouteRoute,
  } as any)
const AuthenticatedApprovedVaultRoute =
  AuthenticatedApprovedVaultRouteImport.update({
    id: '/vault',
    path: '/vault',
    getParentRoute: () => AuthenticatedApprovedRouteRoute,
  } as any)
const ApiPublicHooksScoreShowdownRoute =
  ApiPublicHooksScoreShowdownRouteImport.update({
    id: '/api/public/hooks/score-showdown',
    path: '/api/public/hooks/score-showdown',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/invite': typeof InviteRoute
  '/request-access': typeof RequestAccessRoute
  '/access': typeof AuthenticatedAccessRoute
  '/s/$slug': typeof SSlugRoute
  '/admin': typeof AuthenticatedApprovedAdminRoute
  '/dashboard': typeof AuthenticatedApprovedDashboardRoute
  '/showdown': typeof AuthenticatedApprovedShowdownRoute
  '/vault': typeof AuthenticatedApprovedVaultRoute
  '/api/public/hooks/score-showdown': typeof ApiPublicHooksScoreShowdownRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/invite': typeof InviteRoute
  '/request-access': typeof RequestAccessRoute
  '/access': typeof AuthenticatedAccessRoute
  '/s/$slug': typeof SSlugRoute
  '/admin': typeof AuthenticatedApprovedAdminRoute
  '/dashboard': typeof AuthenticatedApprovedDashboardRoute
  '/showdown': typeof AuthenticatedApprovedShowdownRoute
  '/vault': typeof AuthenticatedApprovedVaultRoute
  '/api/public/hooks/score-showdown': typeof ApiPublicHooksScoreShowdownRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/invite': typeof InviteRoute
  '/request-access': typeof RequestAccessRoute
  '/_authenticated/_approved': typeof AuthenticatedApprovedRouteRouteWithChildren
  '/_authenticated/access': typeof AuthenticatedAccessRoute
  '/s/$slug': typeof SSlugRoute
  '/_authenticated/_approved/admin': typeof AuthenticatedApprovedAdminRoute
  '/_authenticated/_approved/dashboard': typeof AuthenticatedApprovedDashboardRoute
  '/_authenticated/_approved/showdown': typeof AuthenticatedApprovedShowdownRoute
  '/_authenticated/_approved/vault': typeof AuthenticatedApprovedVaultRoute
  '/api/public/hooks/score-showdown': typeof ApiPublicHooksScoreShowdownRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/invite'
    | '/request-access'
    | '/access'
    | '/s/$slug'
    | '/admin'
    | '/dashboard'
    | '/showdown'
    | '/vault'
    | '/api/public/hooks/score-showdown'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/invite'
    | '/request-access'
    | '/access'
    | '/s/$slug'
    | '/admin'
    | '/dashboard'
    | '/showdown'
    | '/vault'
    | '/api/public/hooks/score-showdown'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/invite'
    | '/request-access'
    | '/_authenticated/_approved'
    | '/_authenticated/access'
    | '/s/$slug'
    | '/_authenticated/_approved/admin'
    | '/_authenticated/_approved/dashboard'
    | '/_authenticated/_approved/showdown'
    | '/_authenticated/_approved/vault'
    | '/api/public/hooks/score-showdown'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  InviteRoute: typeof InviteRoute
  RequestAccessRoute: typeof RequestAccessRoute
  SSlugRoute: typeof SSlugRoute
  ApiPublicHooksScoreShowdownRoute: typeof ApiPublicHooksScoreShowdownRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-access': {
      id: '/request-access'
      path: '/request-access'
      fullPath: '/request-access'
      preLoaderRoute: typeof RequestAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_approved': {
      id: '/_authenticated/_approved'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedApprovedRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/access': {
      id: '/_authenticated/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AuthenticatedAccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_approved/admin': {
      id: '/_authenticated/_approved/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedApprovedAdminRouteImport
      parentRoute: typeof AuthenticatedApprovedRouteRoute
    }
    '/_authenticated/_approved/dashboard': {
      id: '/_authenticated/_approved/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedApprovedDashboardRouteImport
      parentRoute: typeof AuthenticatedApprovedRouteRoute
    }
    '/_authenticated/_approved/showdown': {
      id: '/_authenticated/_approved/showdown'
      path: '/showdown'
      fullPath: '/showdown'
      preLoaderRoute: typeof AuthenticatedApprovedShowdownRouteImport
      parentRoute: typeof AuthenticatedApprovedRouteRoute
    }
    '/_authenticated/_approved/vault': {
      id: '/_authenticated/_approved/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AuthenticatedApprovedVaultRouteImport
      parentRoute: typeof AuthenticatedApprovedRouteRoute
    }
    '/api/public/hooks/score-showdown': {
      id: '/api/public/hooks/score-showdown'
      path: '/api/public/hooks/score-showdown'
      fullPath: '/api/public/hooks/score-showdown'
      preLoaderRoute: typeof ApiPublicHooksScoreShowdownRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedApprovedRouteRouteChildren {
  AuthenticatedApprovedAdminRoute: typeof AuthenticatedApprovedAdminRoute
  AuthenticatedApprovedDashboardRoute: typeof AuthenticatedApprovedDashboardRoute
  AuthenticatedApprovedShowdownRoute: typeof AuthenticatedApprovedShowdownRoute
  AuthenticatedApprovedVaultRoute: typeof AuthenticatedApprovedVaultRoute
}

const AuthenticatedApprovedRouteRouteChildren: AuthenticatedApprovedRouteRouteChildren =
  {
    AuthenticatedApprovedAdminRoute: AuthenticatedApprovedAdminRoute,
    AuthenticatedApprovedDashboardRoute: AuthenticatedApprovedDashboardRoute,
    AuthenticatedApprovedShowdownRoute: AuthenticatedApprovedShowdownRoute,
    AuthenticatedApprovedVaultRoute: AuthenticatedApprovedVaultRoute,
  }

const AuthenticatedApprovedRouteRouteWithChildren =
  AuthenticatedApprovedRouteRoute._addFileChildren(
    AuthenticatedApprovedRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApprovedRouteRoute: typeof AuthenticatedApprovedRouteRouteWithChildren
  AuthenticatedAccessRoute: typeof AuthenticatedAccessRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApprovedRouteRoute: AuthenticatedApprovedRouteRouteWithChildren,
  AuthenticatedAccessRoute: AuthenticatedAccessRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  InviteRoute: InviteRoute,
  RequestAccessRoute: RequestAccessRoute,
  SSlugRoute: SSlugRoute,
  ApiPublicHooksScoreShowdownRoute: ApiPublicHooksScoreShowdownRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
